version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # Or whichever version you need
    commands:
      - echo "Installing dependencies if needed"
      - npm install -g aws-cli  # Install AWS CLI if it's not already installed

  build:
    commands:
      - echo "Building beta release"

  post_build:
    commands:
      - echo "Copying beta.html to S3"
      - aws s3 cp beta.html s3://newguyprecisiontx/beta.html --acl public-read
