version: 0.2

phases:
  build:
    commands:
      - echo "Preparing beta release for deployment"

artifacts:
  files:
    - beta.html
  discard-paths: yes  # Ensures only `beta.html` without any path
